/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;
import java.awt.CardLayout; // Import CardLayout
import javax.swing.JFrame; // Import JFrame
/**
 *
 * @author MyBook Z Series
 */
public class FormReservasi extends javax.swing.JFrame {
// Variabel untuk menyimpan CardLayout
    private CardLayout cardLayout;

    /**
     * Creates new form FormTransaksi
     */
    public FormReservasi() {
        initComponents(); // Inisialisasi komponen (dibuat oleh NetBeans)
        
        
        // Panggil fungsi untuk mengatur panel-panel kita
        setupCardLayout();
        
        this.setTitle("Formulir Transaksi"); // Atur judul JFrame
    }
    // Fungsi pembantu untuk membungkus panel agar posisinya di tengah
    private javax.swing.JPanel wrapInCenter(javax.swing.JPanel panelKonten) {
        // 1. Buat panel pembungkus baru
        javax.swing.JPanel wrapper = new javax.swing.JPanel();

        // 2. Set layout pembungkus menjadi GridBagLayout
        // GridBagLayout secara default menaruh komponennya di tengah-tengah (Center)
        wrapper.setLayout(new java.awt.GridBagLayout());

        // 3. Tambahkan panel konten Anda ke dalam pembungkus
        wrapper.add(panelKonten);

        // 4. Kembalikan panel pembungkus
        return wrapper;
    }

    private void setupCardLayout() {
        cardLayout = (CardLayout) (panelKontainer.getLayout());

        PanelCheckIn panelCheckIn = new PanelCheckIn();
        PanelCheckOut panelCheckOut = new PanelCheckOut();
        PanelPemesanan panelBooking = new PanelPemesanan();
        Panelmanajemenbooking panelManajemen = new Panelmanajemenbooking();

        // Tambahkan dengan wrapInCenter
        panelKontainer.add(wrapInCenter(panelCheckIn), "CHECKIN_PANEL");  
        panelKontainer.add(wrapInCenter(panelCheckOut), "CHECKOUT_PANEL");
        panelKontainer.add(wrapInCenter(panelBooking), "Panel_Booking");
        panelKontainer.add(wrapInCenter(panelManajemen), "Panel_Manajemen");

        cardLayout.show(panelKontainer, "CHECKIN_PANEL");
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelKontainer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuBooking = new javax.swing.JMenu();
        menuItemCheckIn = new javax.swing.JMenu();
        menuItemCheckOut = new javax.swing.JMenu();
        manajemenPemesanan = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKontainer.setLayout(new java.awt.CardLayout());

        jMenu1.setText("Navigasi");

        MenuBooking.setText("Formulir Booking");
        MenuBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBookingMouseClicked(evt);
            }
        });
        jMenu1.add(MenuBooking);

        menuItemCheckIn.setText("Formulir Check In");
        menuItemCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemCheckInMouseClicked(evt);
            }
        });
        menuItemCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCheckInActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCheckIn);

        menuItemCheckOut.setText("Formulir Check Out");
        menuItemCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemCheckOutMouseClicked(evt);
            }
        });
        menuItemCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCheckOutActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCheckOut);

        manajemenPemesanan.setText("Manajemen Pemesanan");
        manajemenPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manajemenPemesananMouseClicked(evt);
            }
        });
        jMenu1.add(manajemenPemesanan);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKontainer, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelKontainer, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCheckInActionPerformed
        // Panggil CardLayout untuk menampilkan panel dengan nama "CHECKIN_PANEL"
        cardLayout.show(panelKontainer, "CHECKIN_PANEL");
    }//GEN-LAST:event_menuItemCheckInActionPerformed

    private void menuItemCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCheckOutActionPerformed
        // Panggil CardLayout untuk menampilkan panel dengan nama "CHECKOUT_PANEL"
        cardLayout.show(panelKontainer, "CHECKOUT_PANEL");
    }//GEN-LAST:event_menuItemCheckOutActionPerformed

    private void menuItemCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCheckInMouseClicked
        // TODO add your handling code here:
        // Panggil CardLayout untuk menampilkan panel dengan nama "CHECKIN_PANEL"
        cardLayout.show(panelKontainer, "CHECKIN_PANEL");
    }//GEN-LAST:event_menuItemCheckInMouseClicked

    private void menuItemCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCheckOutMouseClicked
        // Panggil CardLayout untuk menampilkan panel dengan nama "CHECKOUT_PANEL"
        cardLayout.show(panelKontainer, "CHECKOUT_PANEL");
    }//GEN-LAST:event_menuItemCheckOutMouseClicked

    private void MenuBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBookingMouseClicked
        // TODO add your handling code here:
        cardLayout.show(panelKontainer, "Panel_Booking");
    }//GEN-LAST:event_MenuBookingMouseClicked

    private void manajemenPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemenPemesananMouseClicked
        // TODO add your handling code here:
        cardLayout.show(panelKontainer, "Panel_Manajemen");
    }//GEN-LAST:event_manajemenPemesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBooking;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu manajemenPemesanan;
    private javax.swing.JMenu menuItemCheckIn;
    private javax.swing.JMenu menuItemCheckOut;
    private javax.swing.JPanel panelKontainer;
    // End of variables declaration//GEN-END:variables
}
