
package MyApp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat; // Untuk format mata uang
import java.util.Locale; // Untuk format mata uang Indonesia
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormLaporan extends javax.swing.JFrame {
    private DefaultTableModel modelTabel;
    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        this.setTitle("Laporan Riwayat Reservasi");
        
        // Atur agar form muncul di tengah
        this.setLocationRelativeTo(null);
        
        // Siapkan tabel
        inisialisasiTabel();
        
        // Muat data laporan
        loadDataLaporan();
    }
    // Fungsi untuk inisialisasi JTable
    private void inisialisasiTabel() {
        modelTabel = new DefaultTableModel();
        
        // Tambahkan kolom-kolom yang relevan untuk laporan
        modelTabel.addColumn("ID Reservasi");
        modelTabel.addColumn("Nama Tamu");
        modelTabel.addColumn("No. Kamar");
        modelTabel.addColumn("Tgl. Check-In");
        modelTabel.addColumn("Tgl. Check-Out");
        modelTabel.addColumn("Total Tagihan");
        
        tblLaporan.setModel(modelTabel);
    }

    // Fungsi untuk memuat data laporan dari database
    private void loadDataLaporan() {
        // Kosongkan tabel
        modelTabel.setRowCount(0);
        
        // Siapkan format mata uang Rupiah
        NumberFormat formatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        
        Connection koneksi = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            koneksi = Koneksi.getKoneksi();
            
            // Ini adalah query JOIN 3 tabel
            // Kita ambil data dari reservasi, tamu, dan kamar
            // Kita filter HANYA reservasi yang statusnya 'Selesai'
            String sql = "SELECT r.id_reservasi, t.nama_tamu, k.no_kamar, r.tgl_checkin, r.tgl_checkout, r.total_biaya " +
                         "FROM tabel_reservasi r " +
                         "JOIN tabel_tamu t ON r.id_tamu = t.id_tamu " +
                         "JOIN tabel_kamar k ON r.id_kamar = k.id_kamar " +
                         "WHERE r.status_reservasi = 'Selesai' " +
                         "ORDER BY r.tgl_checkout DESC"; // Urutkan berdasarkan yg terbaru
            
            pstmt = koneksi.prepareStatement(sql);
            rs = pstmt.executeQuery();

            // Looping data dari ResultSet dan tambahkan ke model tabel
            while (rs.next()) {
                Object[] baris = new Object[6];
                baris[0] = rs.getInt("id_reservasi");
                baris[1] = rs.getString("nama_tamu");
                baris[2] = rs.getString("no_kamar");
                baris[3] = rs.getString("tgl_checkin");
                baris[4] = rs.getString("tgl_checkout");
                
                // Format total biaya ke Rupiah
                double total = rs.getDouble("total_biaya");
                baris[5] = formatter.format(total);
                
                modelTabel.addRow(baris);
            }
            
            // Cek jika tidak ada data
            if (modelTabel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Belum ada riwayat reservasi yang selesai.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat memuat data laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (rs != null) rs.close(); } catch (Exception e) {}
            try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        J = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan Riwayat Reservasi");

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        J.setViewportView(tblLaporan);

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(J, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane J;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
