/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MyApp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MyBook Z Series
 */
public class Panelmanajemenbooking extends javax.swing.JPanel {

    /**
     * Creates new form Panelmanajemenbookinng
     */
   private DefaultTableModel modelTabel;
    
    // Variabel untuk menyimpan ID dan status baris yang dipilih
    private int idBookingDipilih = 0;
    private String statusBookingDipilih = "";

    /**
     * Creates new form PanelManajemenBooking
     */
    public Panelmanajemenbooking() {
        initComponents();
        inisialisasiTabel();
        loadDataBooking();
        
        // Atur status tombol awal
        clearState();
    }

    // Fungsi untuk mengatur kolom-kolom tabel
    private void inisialisasiTabel() {
        modelTabel = new DefaultTableModel();
        
        modelTabel.addColumn("ID"); // Kolom 0 (bisa disembunyikan)
        modelTabel.addColumn("Nama Tamu");
        modelTabel.addColumn("No. Kamar");
        modelTabel.addColumn("Tgl Check-In");
        modelTabel.addColumn("Tgl Check-Out");
        modelTabel.addColumn("Status"); // Booking, Aktif, Selesai
        
        tblBooking.setModel(modelTabel);
        
        // Sembunyikan kolom ID (opsional, tapi rapi)
        tblBooking.getColumnModel().getColumn(0).setMinWidth(0);
        tblBooking.getColumnModel().getColumn(0).setMaxWidth(0);
        tblBooking.getColumnModel().getColumn(0).setWidth(0);
    }

    // Fungsi untuk memuat data dari database
    private void loadDataBooking() {
        // Hapus data lama
        modelTabel.setRowCount(0);
        
        Connection koneksi = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            koneksi = Koneksi.getKoneksi();
            
            // Query JOIN 3 tabel untuk data yang lengkap
            String sql = "SELECT r.id_reservasi, t.nama_tamu, k.no_kamar, r.tgl_checkin, r.tgl_checkout, r.status_reservasi " +
                         "FROM tabel_reservasi r " +
                         "JOIN tabel_tamu t ON r.id_tamu = t.id_tamu " +
                         "JOIN tabel_kamar k ON r.id_kamar = k.id_kamar " +
                         "WHERE r.status_reservasi != 'Selesai' " + // Tampilkan yg 'Booking' atau 'Aktif'
                         "ORDER BY r.tgl_checkin ASC"; 
            
            pstmt = koneksi.prepareStatement(sql);
            rs = pstmt.executeQuery();

           while (rs.next()) {
                // 1. Ambil data tanggal ke variabel
                java.sql.Date tglIn = rs.getDate("tgl_checkin");
                java.sql.Date tglOut = rs.getDate("tgl_checkout");

                // 2. Cek apakah null. Jika null, ganti dengan string "-", jika tidak, ubah ke string
                String checkInStr = (tglIn == null) ? "-" : tglIn.toString();
                String checkOutStr = (tglOut == null) ? "-" : tglOut.toString(); // Ini perbaikan utamanya

                // 3. Masukkan ke tabel menggunakan string yang sudah aman
                modelTabel.addRow(new Object[]{
                    rs.getInt("id_reservasi"),
                    rs.getString("nama_tamu"),
                    rs.getString("no_kamar"),
                    checkInStr,  // Aman
                    checkOutStr, // Aman
                    rs.getString("status_reservasi")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error memuat data: " + e.getMessage());
        } finally {
            try { if (rs != null) rs.close(); if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        }
    }
    
    // Fungsi untuk membersihkan seleksi
    private void clearState() {
        idBookingDipilih = 0;
        statusBookingDipilih = "";
        tblBooking.clearSelection(); // Hapus seleksi di tabel
        btnHapus.setEnabled(false); // Matikan tombol hapus
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manajemen Pemesanan");

        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooking);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookingMouseClicked
        // TODO add your handling code here:
        int baris = tblBooking.getSelectedRow();
        if (baris == -1) {
            return;
        }
        
        // Ambil data dari baris yang diklik
        // Kolom 0 adalah ID (int), Kolom 5 adalah Status (String)
        idBookingDipilih = (int) modelTabel.getValueAt(baris, 0);
        statusBookingDipilih = (String) modelTabel.getValueAt(baris, 5);
        
        // Aktifkan tombol Hapus
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblBookingMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDataBooking();
        clearState();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (idBookingDipilih == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel.");
            return;
        }
        
        // ATURAN BISNIS: Anda hanya boleh menghapus reservasi yang statusnya 'Booking'.
        // Jika sudah 'Aktif' (sedang check-in), harus lewat alur Check-Out.
        if (!statusBookingDipilih.equals("Booking")) {
            JOptionPane.showMessageDialog(this, "Data ini tidak bisa dihapus karena tamu sudah Check-In (status 'Aktif').\n"
                    + "Gunakan formulir Check-Out untuk menyelesaikan.", "Aksi Ditolak", JOptionPane.ERROR_MESSAGE);
            clearState();
            return;
        }
        
        // Konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this, 
                "Anda yakin ingin membatalkan booking ini?", 
                "Konfirmasi Pembatalan", 
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (pilihan == JOptionPane.YES_OPTION) {
            Connection koneksi = null;
            PreparedStatement pstmt = null;
            try {
                koneksi = Koneksi.getKoneksi();
                String sql = "DELETE FROM tabel_reservasi WHERE id_reservasi = ?";
                pstmt = koneksi.prepareStatement(sql);
                pstmt.setInt(1, idBookingDipilih);
                
                int hasil = pstmt.executeUpdate();
                if (hasil > 0) {
                    JOptionPane.showMessageDialog(this, "Booking berhasil dibatalkan.");
                    loadDataBooking(); // Muat ulang data
                    clearState();      // Bersihkan seleksi
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error menghapus data: " + e.getMessage());
            } finally {
                 try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBooking;
    // End of variables declaration//GEN-END:variables
}
